# Generated by Django 4.1.3 on 2022-11-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylinks',
            name='link_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mylinks',
            name='link_url',
            field=models.CharField(max_length=100),
        ),
    ]
